---
# Do main role initialization

- name: Reset internal variables
  ansible.builtin.set_fact:
    # List of systemd service names corresponding to disk mounts
    disks_pending_systemd_mounts: []

    # List of fstab-managed mount points that should be re-mounted
    disks_pending_fstab_mounts: []

    # Information written to local host facts at /etc/ansible/facts.d/disk_part.fact
    #  - Built during role execution
    disks_fact_data: []
