---
# Mount a partition using a systemd unit

- name: Gather mount information for duplicate detection
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "mounts"

- name: Generate systemd unit name
  ansible.builtin.command:
    cmd: 'systemd-escape -p --suffix=mount "{{ disks_disk_config.mount_path }}"'
  register: disks_systemd_filename_raw
  changed_when: false

- name: Format unit name data
  ansible.builtin.set_fact:
    disks_systemd_filename: "{{ disks_systemd_filename_raw.stdout | trim }}"

- name: Check for duplicate mounts before configuring systemd mount
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/unmount_duplicates.yml"

- name: Configure disk mount
  when: disks_disk_config.state in ['present', 'mounted']
  block:
    - name: Install disk mount systemd unit ({{ disks_systemd_filename }})
      become: true
      ansible.builtin.template:
        src: templates/etc/systemd/system/data_disk.mount.j2
        dest: /etc/systemd/system/{{ disks_systemd_filename }}
      register: disks_systemd_install_output

    # NOTE it's desired to mount/remount disks in-line in order to ensure that they are accessible for later plays
    #      an argument could be made for using flush_handlers at the end of this role, but here we are...

    - name: Disk is mounted
      when:
        - disks_systemd_install_output is not changed
        - disks_disk_config.state == 'mounted'
      become: true
      ansible.builtin.systemd_service:
        name: "{{ disks_systemd_filename }}"
        state: started
        daemon_reload: true

    - name: Disk is remounted
      when:
        - disks_systemd_install_output is changed
        - disks_disk_config.state == 'mounted'
        - disks_allow_remount | default(true)
      become: true
      ansible.builtin.systemd_service:
        state: restarted
        name: "{{ disks_systemd_filename }}"

- name: Unmount disk
  when: disks_disk_config.state in ["absent", "unmounted"]
  vars:
    __disks_unmount_mount_path: "{{ disks_disk_config.mount_path }}"
    __disks_unmount_remove_config: "{{ disks_disk_config.state == 'absent' }}"
    __disks_unmount_mount_type: "systemd"
    __disks_unmount_systemd_unit: "{{ disks_systemd_filename }}"
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/unmount_disk.yml"
